# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 20:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20170927_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(choices=[('made', 'Payment made'), ('missed', 'Payment missed')], max_length=6),
        ),
    ]
